# Generated by Django 5.0.2 on 2024-04-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
