# Generated by Django 5.0.2 on 2024-04-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='comments',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comment'),
        ),
    ]
